_extends: .github
name-template: '$RESOLVED_VERSION'
tag-template: 'buildnumber-maven-plugin-$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES